# Site
name: "Historical Transparency Society"
title: "Historical Transparency Society"
description: "A volunteer-led organization, dedicated to preserving accurate history."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: articles/:title/
email: wowthemesnet@gmail.com

# Authors
authors:
  neer:
    name: Bibswan Dev Biswas
    display_name: Bibswan Dev Biswas
    avatar: 'assets/images/avatars/neer.jpg'
    facebook: https://www.facebook.com/bibswan.nir.biswas
    linkedin: https://www.linkedin.com/in/Bibswan%20Deb%20Biswas%20Nir
    description: "Law, University of Dhaka"
  rodaba:
    name: Rodaba Jaman
    display_name: Rodaba Jaman
    avatar: 'assets/images/avatars/rodaba.jpg'
    facebook: https://www.facebook.com/jaman.rodaba
    description: "Women and Gender Studies, University of Dhaka"
  noman:
    name: Abdullah All Noman
    display_name: Abdullah All Noman
    avatar: 'assets/images/avatars/noman.jpg'
    facebook: https://www.facebook.com/abdullahall.noman.3386585
    description: "Public Administration, University of Dhaka"
  tanim:
    name: Saleh Mahmud Tanim
    display_name: Saleh Mahmud Tanim
    avatar: 'assets/images/avatars/tanim.jpg'
    email: smtanim915@gmail.com
    linkedin: https://www.linkedin.com/in/SM%20Tanim
    facebook: https://www.facebook.com/salehmahmud.tanim.5
    description: "Applied Mathematics, University of Dhaka"
  ayan:
    name: Ayan Abdullah
    display_name: Ayan Abdullah
    avatar: 'assets/images/avatars/ayan.jpg'
    description: "Independent Researcher"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
